// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/breedingparams.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BreedingParams struct {
	ParentOne            int64    `protobuf:"varint,1,opt,name=parentOne,proto3" json:"parentOne,omitempty"`
	ParentTwo            int64    `protobuf:"varint,2,opt,name=parentTwo,proto3" json:"parentTwo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *BreedingParams) Reset()         { *m = BreedingParams{} }
func (m *BreedingParams) String() string { return proto.CompactTextString(m) }
func (*BreedingParams) ProtoMessage()    {}
func (*BreedingParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_89c4ad8b710f6650, []int{0}
}

func (m *BreedingParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreedingParams.Unmarshal(m, b)
}
func (m *BreedingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreedingParams.Marshal(b, m, deterministic)
}
func (m *BreedingParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreedingParams.Merge(m, src)
}
func (m *BreedingParams) XXX_Size() int {
	return xxx_messageInfo_BreedingParams.Size(m)
}
func (m *BreedingParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BreedingParams.DiscardUnknown(m)
}

var xxx_messageInfo_BreedingParams proto.InternalMessageInfo

func (m *BreedingParams) GetParentOne() int64 {
	if m != nil {
		return m.ParentOne
	}
	return 0
}

func (m *BreedingParams) GetParentTwo() int64 {
	if m != nil {
		return m.ParentTwo
	}
	return 0
}

func init() {
	proto.RegisterType((*BreedingParams)(nil), "protobuf.BreedingParams")
}

func init() { proto.RegisterFile("protobuf/breedingparams.proto", fileDescriptor_89c4ad8b710f6650) }

var fileDescriptor_89c4ad8b710f6650 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0x2a, 0x4a, 0x4d, 0x4d, 0xc9, 0xcc, 0x4b, 0x2f, 0x48, 0x2c,
	0x4a, 0xcc, 0x2d, 0xd6, 0x03, 0x8b, 0x0b, 0x71, 0xc0, 0xa4, 0x95, 0x7c, 0xb8, 0xf8, 0x9c, 0xa0,
	0x2a, 0x02, 0xc0, 0x2a, 0x84, 0x64, 0xb8, 0x38, 0x0b, 0x12, 0x8b, 0x52, 0xf3, 0x4a, 0xfc, 0xf3,
	0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x10, 0x02, 0x08, 0xd9, 0x90, 0xf2, 0x7c, 0x09,
	0x26, 0x64, 0xd9, 0x90, 0xf2, 0xfc, 0x24, 0x36, 0xb0, 0xb9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc0, 0x12, 0x5b, 0xc5, 0x7f, 0x00, 0x00, 0x00,
}
