// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/etherflower.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EtherFlower struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Rarity               int32    `protobuf:"varint,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	RarityTier           int32    `protobuf:"varint,4,opt,name=rarityTier,proto3" json:"rarityTier,omitempty"`
	FlowerData           *Flower  `protobuf:"bytes,5,opt,name=flowerData,proto3" json:"flowerData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *EtherFlower) Reset()         { *m = EtherFlower{} }
func (m *EtherFlower) String() string { return proto.CompactTextString(m) }
func (*EtherFlower) ProtoMessage()    {}
func (*EtherFlower) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fdc52cc0f092cf, []int{0}
}

func (m *EtherFlower) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EtherFlower.Unmarshal(m, b)
}
func (m *EtherFlower) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EtherFlower.Marshal(b, m, deterministic)
}
func (m *EtherFlower) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EtherFlower.Merge(m, src)
}
func (m *EtherFlower) XXX_Size() int {
	return xxx_messageInfo_EtherFlower.Size(m)
}
func (m *EtherFlower) XXX_DiscardUnknown() {
	xxx_messageInfo_EtherFlower.DiscardUnknown(m)
}

var xxx_messageInfo_EtherFlower proto.InternalMessageInfo

func (m *EtherFlower) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *EtherFlower) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *EtherFlower) GetRarity() int32 {
	if m != nil {
		return m.Rarity
	}
	return 0
}

func (m *EtherFlower) GetRarityTier() int32 {
	if m != nil {
		return m.RarityTier
	}
	return 0
}

func (m *EtherFlower) GetFlowerData() *Flower {
	if m != nil {
		return m.FlowerData
	}
	return nil
}

func init() {
	proto.RegisterType((*EtherFlower)(nil), "protobuf.EtherFlower")
}

func init() { proto.RegisterFile("protobuf/etherflower.proto", fileDescriptor_69fdc52cc0f092cf) }

var fileDescriptor_69fdc52cc0f092cf = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0x2d, 0xc9, 0x48, 0x2d, 0x4a, 0xcb, 0xc9, 0x2f, 0x4f, 0x2d,
	0xd2, 0x03, 0x0b, 0x0a, 0x71, 0xc0, 0xe4, 0xa4, 0x44, 0xe1, 0xaa, 0x90, 0x15, 0x28, 0xcd, 0x65,
	0xe4, 0xe2, 0x76, 0x05, 0x69, 0x73, 0x03, 0x8b, 0x0a, 0xf1, 0x71, 0x31, 0x79, 0xba, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x30, 0x07, 0x31, 0x79, 0xba, 0x08, 0x89, 0x70, 0xb1, 0xe6, 0x97, 0xe7, 0xa5,
	0x16, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0x45, 0x89,
	0x45, 0x99, 0x25, 0x95, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x50, 0x9e, 0x90, 0x1c, 0x17,
	0x17, 0x84, 0x15, 0x92, 0x99, 0x5a, 0x24, 0xc1, 0x02, 0x96, 0x43, 0x12, 0x11, 0x32, 0xe0, 0xe2,
	0x82, 0xd8, 0xee, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa0, 0x07,
	0x73, 0x99, 0x1e, 0xc4, 0x0d, 0x41, 0x48, 0x6a, 0x92, 0xd8, 0xc0, 0x92, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x26, 0x2b, 0x54, 0x80, 0xe5, 0x00, 0x00, 0x00,
}
