// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/gametile.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameTile_Content_Type int32

const (
	GameTile_Content_WATERED GameTile_Content_Type = 0
	GameTile_Content_TILLED  GameTile_Content_Type = 1
	GameTile_Content_PLANTED GameTile_Content_Type = 2
	GameTile_Content_TOPPER  GameTile_Content_Type = 3
)

var GameTile_Content_Type_name = map[int32]string{
	0: "WATERED",
	1: "TILLED",
	2: "PLANTED",
	3: "TOPPER",
}

var GameTile_Content_Type_value = map[string]int32{
	"WATERED": 0,
	"TILLED":  1,
	"PLANTED": 2,
	"TOPPER":  3,
}

func (x GameTile_Content_Type) String() string {
	return proto.EnumName(GameTile_Content_Type_name, int32(x))
}

func (GameTile_Content_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_117e465bbcd25cf2, []int{0, 0, 0}
}

type GameTile_Content_GrowthStage int32

const (
	GameTile_Content_SEEDLING GameTile_Content_GrowthStage = 0
	GameTile_Content_SPROUT   GameTile_Content_GrowthStage = 1
	GameTile_Content_SAPLING  GameTile_Content_GrowthStage = 2
	GameTile_Content_ADULT    GameTile_Content_GrowthStage = 3
)

var GameTile_Content_GrowthStage_name = map[int32]string{
	0: "SEEDLING",
	1: "SPROUT",
	2: "SAPLING",
	3: "ADULT",
}

var GameTile_Content_GrowthStage_value = map[string]int32{
	"SEEDLING": 0,
	"SPROUT":   1,
	"SAPLING":  2,
	"ADULT":    3,
}

func (x GameTile_Content_GrowthStage) String() string {
	return proto.EnumName(GameTile_Content_GrowthStage_name, int32(x))
}

func (GameTile_Content_GrowthStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_117e465bbcd25cf2, []int{0, 0, 1}
}

// Database key: tile position "X,Y"
type GameTile struct {
	X                    int32               `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32               `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Owner                string              `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	LastChangedTimestamp int64               `protobuf:"varint,4,opt,name=last_changed_timestamp,json=lastChangedTimestamp,proto3" json:"last_changed_timestamp,omitempty"`
	Content              []*GameTile_Content `protobuf:"bytes,9,rep,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" datastore:"-"`
	XXX_unrecognized     []byte              `json:"-" datastore:"-"`
	XXX_sizecache        int32               `json:"-" datastore:"-"`
}

func (m *GameTile) Reset()         { *m = GameTile{} }
func (m *GameTile) String() string { return proto.CompactTextString(m) }
func (*GameTile) ProtoMessage()    {}
func (*GameTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_117e465bbcd25cf2, []int{0}
}

func (m *GameTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTile.Unmarshal(m, b)
}
func (m *GameTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTile.Marshal(b, m, deterministic)
}
func (m *GameTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTile.Merge(m, src)
}
func (m *GameTile) XXX_Size() int {
	return xxx_messageInfo_GameTile.Size(m)
}
func (m *GameTile) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTile.DiscardUnknown(m)
}

var xxx_messageInfo_GameTile proto.InternalMessageInfo

func (m *GameTile) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GameTile) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *GameTile) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GameTile) GetLastChangedTimestamp() int64 {
	if m != nil {
		return m.LastChangedTimestamp
	}
	return 0
}

func (m *GameTile) GetContent() []*GameTile_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type GameTile_Content struct {
	Type                 GameTile_Content_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=protobuf.GameTile_Content_Type" json:"type,omitempty"`
	EthId                int64                        `protobuf:"varint,2,opt,name=eth_id,json=ethId,proto3" json:"eth_id,omitempty"`
	GrowthStage          GameTile_Content_GrowthStage `protobuf:"varint,3,opt,name=growth_stage,json=growthStage,proto3,enum=protobuf.GameTile_Content_GrowthStage" json:"growth_stage,omitempty"`
	TopperId             int64                        `protobuf:"varint,4,opt,name=topper_id,json=topperId,proto3" json:"topper_id,omitempty"`
	Timestamp            int64                        `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-" datastore:"-"`
	XXX_unrecognized     []byte                       `json:"-" datastore:"-"`
	XXX_sizecache        int32                        `json:"-" datastore:"-"`
}

func (m *GameTile_Content) Reset()         { *m = GameTile_Content{} }
func (m *GameTile_Content) String() string { return proto.CompactTextString(m) }
func (*GameTile_Content) ProtoMessage()    {}
func (*GameTile_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_117e465bbcd25cf2, []int{0, 0}
}

func (m *GameTile_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTile_Content.Unmarshal(m, b)
}
func (m *GameTile_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTile_Content.Marshal(b, m, deterministic)
}
func (m *GameTile_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTile_Content.Merge(m, src)
}
func (m *GameTile_Content) XXX_Size() int {
	return xxx_messageInfo_GameTile_Content.Size(m)
}
func (m *GameTile_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTile_Content.DiscardUnknown(m)
}

var xxx_messageInfo_GameTile_Content proto.InternalMessageInfo

func (m *GameTile_Content) GetType() GameTile_Content_Type {
	if m != nil {
		return m.Type
	}
	return GameTile_Content_WATERED
}

func (m *GameTile_Content) GetEthId() int64 {
	if m != nil {
		return m.EthId
	}
	return 0
}

func (m *GameTile_Content) GetGrowthStage() GameTile_Content_GrowthStage {
	if m != nil {
		return m.GrowthStage
	}
	return GameTile_Content_SEEDLING
}

func (m *GameTile_Content) GetTopperId() int64 {
	if m != nil {
		return m.TopperId
	}
	return 0
}

func (m *GameTile_Content) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuf.GameTile_Content_Type", GameTile_Content_Type_name, GameTile_Content_Type_value)
	proto.RegisterEnum("protobuf.GameTile_Content_GrowthStage", GameTile_Content_GrowthStage_name, GameTile_Content_GrowthStage_value)
	proto.RegisterType((*GameTile)(nil), "protobuf.GameTile")
	proto.RegisterType((*GameTile_Content)(nil), "protobuf.GameTile.Content")
}

func init() { proto.RegisterFile("protobuf/gametile.proto", fileDescriptor_117e465bbcd25cf2) }

var fileDescriptor_117e465bbcd25cf2 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4f, 0x8b, 0x9b, 0x40,
	0x18, 0xc6, 0xeb, 0xbf, 0x44, 0x5f, 0xc3, 0x22, 0xc3, 0xb6, 0x95, 0x6d, 0xa1, 0x92, 0x43, 0xf1,
	0x64, 0x21, 0xbb, 0x87, 0xde, 0x8a, 0xac, 0x12, 0x04, 0xd9, 0xc8, 0x38, 0xa1, 0x47, 0x31, 0x71,
	0xaa, 0x42, 0xfc, 0x83, 0x99, 0x92, 0x78, 0xec, 0x97, 0xec, 0xe7, 0x29, 0xce, 0x54, 0xd2, 0x4b,
	0xf7, 0xf8, 0x3c, 0xbf, 0x67, 0xde, 0x79, 0xde, 0x17, 0xde, 0xf7, 0x43, 0xc7, 0xba, 0xc3, 0xcf,
	0x1f, 0x5f, 0xca, 0xbc, 0xa1, 0xac, 0x3e, 0x51, 0x8f, 0x3b, 0x48, 0x9f, 0xc1, 0xfa, 0x97, 0x0a,
	0xfa, 0x36, 0x6f, 0x28, 0xa9, 0x4f, 0x14, 0xad, 0x40, 0xba, 0xda, 0x92, 0x23, 0xb9, 0x1a, 0x96,
	0xae, 0x93, 0x1a, 0x6d, 0x59, 0xa8, 0x11, 0xdd, 0x83, 0xd6, 0x5d, 0x5a, 0x3a, 0xd8, 0x8a, 0x23,
	0xb9, 0x06, 0x16, 0x02, 0x3d, 0xc1, 0xbb, 0x53, 0x7e, 0x66, 0xd9, 0xb1, 0xca, 0xdb, 0x92, 0x16,
	0x19, 0xab, 0x1b, 0x7a, 0x66, 0x79, 0xd3, 0xdb, 0xaa, 0x23, 0xb9, 0x0a, 0xbe, 0x9f, 0xe8, 0xb3,
	0x80, 0x64, 0x66, 0xe8, 0x09, 0x96, 0xc7, 0xae, 0x65, 0xb4, 0x65, 0xb6, 0xe1, 0x28, 0xae, 0xb9,
	0x79, 0xf0, 0xe6, 0x42, 0xde, 0x5c, 0xc6, 0x7b, 0x16, 0x09, 0x3c, 0x47, 0x1f, 0x7e, 0xcb, 0xb0,
	0xfc, 0x6b, 0xa2, 0x47, 0x50, 0xd9, 0xd8, 0x53, 0x5e, 0xf6, 0x6e, 0xf3, 0xe9, 0xff, 0xcf, 0x3d,
	0x32, 0xf6, 0x14, 0xf3, 0x30, 0x7a, 0x0b, 0x0b, 0xca, 0xaa, 0xac, 0x2e, 0xf8, 0x56, 0x0a, 0xd6,
	0x28, 0xab, 0xa2, 0x02, 0x45, 0xb0, 0x2a, 0x87, 0xee, 0xc2, 0xaa, 0xec, 0xcc, 0xf2, 0x92, 0xf2,
	0x05, 0xef, 0x36, 0x9f, 0x5f, 0x99, 0xb9, 0xe5, 0xf1, 0x74, 0x4a, 0x63, 0xb3, 0xbc, 0x09, 0xf4,
	0x01, 0x0c, 0xd6, 0xf5, 0x3d, 0x1d, 0xa6, 0x4f, 0xc4, 0x05, 0x74, 0x61, 0x44, 0x05, 0xfa, 0x08,
	0xc6, 0xed, 0x3c, 0x1a, 0x87, 0x37, 0x63, 0xfd, 0x15, 0xd4, 0xa9, 0x2a, 0x32, 0x61, 0xf9, 0xdd,
	0x27, 0x21, 0x0e, 0x03, 0xeb, 0x0d, 0x02, 0x58, 0x90, 0x28, 0x8e, 0xc3, 0xc0, 0x92, 0x26, 0x90,
	0xc4, 0xfe, 0x0b, 0x09, 0x03, 0x4b, 0xe6, 0x60, 0x97, 0x24, 0x21, 0xb6, 0x94, 0xf5, 0x37, 0x30,
	0xff, 0x29, 0x84, 0x56, 0xa0, 0xa7, 0x61, 0x18, 0xc4, 0xd1, 0xcb, 0x56, 0x4c, 0x48, 0x13, 0xbc,
	0xdb, 0x13, 0x31, 0x21, 0xf5, 0x13, 0x0e, 0x64, 0x64, 0x80, 0xe6, 0x07, 0xfb, 0x98, 0x58, 0xca,
	0x61, 0xc1, 0x37, 0x7d, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xac, 0xef, 0x10, 0x2f, 0x02,
	0x00, 0x00,
}
