// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/like.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Like_Type int32

const (
	Like_MARKET   Like_Type = 0
	Like_ETHEREUM Like_Type = 1
)

var Like_Type_name = map[int32]string{
	0: "MARKET",
	1: "ETHEREUM",
}

var Like_Type_value = map[string]int32{
	"MARKET":   0,
	"ETHEREUM": 1,
}

func (x Like_Type) String() string {
	return proto.EnumName(Like_Type_name, int32(x))
}

func (Like_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d05dab316a413b21, []int{0, 0}
}

// Database key is ID
type Like struct {
	Likes                int64     `protobuf:"varint,1,opt,name=likes,proto3" json:"likes,omitempty"`
	Type                 Like_Type `protobuf:"varint,2,opt,name=type,proto3,enum=protobuf.Like_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" datastore:"-"`
	XXX_unrecognized     []byte    `json:"-" datastore:"-"`
	XXX_sizecache        int32     `json:"-" datastore:"-"`
}

func (m *Like) Reset()         { *m = Like{} }
func (m *Like) String() string { return proto.CompactTextString(m) }
func (*Like) ProtoMessage()    {}
func (*Like) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05dab316a413b21, []int{0}
}

func (m *Like) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Like.Unmarshal(m, b)
}
func (m *Like) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Like.Marshal(b, m, deterministic)
}
func (m *Like) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Like.Merge(m, src)
}
func (m *Like) XXX_Size() int {
	return xxx_messageInfo_Like.Size(m)
}
func (m *Like) XXX_DiscardUnknown() {
	xxx_messageInfo_Like.DiscardUnknown(m)
}

var xxx_messageInfo_Like proto.InternalMessageInfo

func (m *Like) GetLikes() int64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Like) GetType() Like_Type {
	if m != nil {
		return m.Type
	}
	return Like_MARKET
}

func init() {
	proto.RegisterEnum("protobuf.Like_Type", Like_Type_name, Like_Type_value)
	proto.RegisterType((*Like)(nil), "protobuf.Like")
}

func init() { proto.RegisterFile("protobuf/like.proto", fileDescriptor_d05dab316a413b21) }

var fileDescriptor_d05dab316a413b21 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0xcf, 0xc9, 0xcc, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0x38, 0x60, 0x82,
	0x4a, 0xe9, 0x5c, 0x2c, 0x3e, 0x99, 0xd9, 0xa9, 0x42, 0x22, 0x5c, 0xac, 0x20, 0xf9, 0x62, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x08, 0x47, 0x48, 0x9d, 0x8b, 0xa5, 0xa4, 0xb2, 0x20, 0x55,
	0x82, 0x49, 0x81, 0x51, 0x83, 0xcf, 0x48, 0x58, 0x0f, 0xa6, 0x4d, 0x0f, 0xa4, 0x47, 0x2f, 0xa4,
	0xb2, 0x20, 0x35, 0x08, 0xac, 0x40, 0x49, 0x81, 0x8b, 0x05, 0xc4, 0x13, 0xe2, 0xe2, 0x62, 0xf3,
	0x75, 0x0c, 0xf2, 0x76, 0x0d, 0x11, 0x60, 0x10, 0xe2, 0xe1, 0xe2, 0x70, 0x0d, 0xf1, 0x70, 0x0d,
	0x72, 0x0d, 0xf5, 0x15, 0x60, 0x4c, 0x62, 0x03, 0xeb, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x21, 0x1e, 0x4a, 0xdb, 0x90, 0x00, 0x00, 0x00,
}
