// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/mintrecord.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MintRecord_Status int32

const (
	MintRecord_STATUS_NONE        MintRecord_Status = 0
	MintRecord_STATUS_STARTED     MintRecord_Status = 1
	MintRecord_STATUS_COMPLETED   MintRecord_Status = 2
	MintRecord_STATUS_ERR         MintRecord_Status = 5
	MintRecord_STATUS_ERR_TIMEOUT MintRecord_Status = 6
)

var MintRecord_Status_name = map[int32]string{
	0: "STATUS_NONE",
	1: "STATUS_STARTED",
	2: "STATUS_COMPLETED",
	5: "STATUS_ERR",
	6: "STATUS_ERR_TIMEOUT",
}

var MintRecord_Status_value = map[string]int32{
	"STATUS_NONE":        0,
	"STATUS_STARTED":     1,
	"STATUS_COMPLETED":   2,
	"STATUS_ERR":         5,
	"STATUS_ERR_TIMEOUT": 6,
}

func (x MintRecord_Status) String() string {
	return proto.EnumName(MintRecord_Status_name, int32(x))
}

func (MintRecord_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_219aa6949c8ae29b, []int{0, 0}
}

type MintRecord_PaymentDetails_PaymentType int32

const (
	MintRecord_PaymentDetails_TYPE_ETH  MintRecord_PaymentDetails_PaymentType = 0
	MintRecord_PaymentDetails_TYPE_SEED MintRecord_PaymentDetails_PaymentType = 1
)

var MintRecord_PaymentDetails_PaymentType_name = map[int32]string{
	0: "TYPE_ETH",
	1: "TYPE_SEED",
}

var MintRecord_PaymentDetails_PaymentType_value = map[string]int32{
	"TYPE_ETH":  0,
	"TYPE_SEED": 1,
}

func (x MintRecord_PaymentDetails_PaymentType) String() string {
	return proto.EnumName(MintRecord_PaymentDetails_PaymentType_name, int32(x))
}

func (MintRecord_PaymentDetails_PaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_219aa6949c8ae29b, []int{0, 0, 0}
}

type MintRecord struct {
	Status                 MintRecord_Status          `protobuf:"varint,1,opt,name=status,proto3,enum=protobuf.MintRecord_Status" json:"status,omitempty"`
	StatusMessage          string                     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	PayerAddress           string                     `protobuf:"bytes,3,opt,name=payerAddress,proto3" json:"payerAddress,omitempty"`
	PaymentDetails         *MintRecord_PaymentDetails `protobuf:"bytes,4,opt,name=paymentDetails,proto3" json:"paymentDetails,omitempty"`
	MintingTransactionHash string                     `protobuf:"bytes,5,opt,name=mintingTransactionHash,proto3" json:"mintingTransactionHash,omitempty"`
	MintingDetails         *MintRecord_MintingDetails `protobuf:"bytes,6,opt,name=mintingDetails,proto3" json:"mintingDetails,omitempty"`
	Timestamps             *MintRecord_Timestamps     `protobuf:"bytes,8,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	FlowerData             *Flower                    `protobuf:"bytes,9,opt,name=flowerData,proto3" json:"flowerData,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                   `json:"-" datastore:"-"`
	XXX_unrecognized       []byte                     `json:"-" datastore:"-"`
	XXX_sizecache          int32                      `json:"-" datastore:"-"`
}

func (m *MintRecord) Reset()         { *m = MintRecord{} }
func (m *MintRecord) String() string { return proto.CompactTextString(m) }
func (*MintRecord) ProtoMessage()    {}
func (*MintRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_219aa6949c8ae29b, []int{0}
}

func (m *MintRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintRecord.Unmarshal(m, b)
}
func (m *MintRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintRecord.Marshal(b, m, deterministic)
}
func (m *MintRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintRecord.Merge(m, src)
}
func (m *MintRecord) XXX_Size() int {
	return xxx_messageInfo_MintRecord.Size(m)
}
func (m *MintRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MintRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MintRecord proto.InternalMessageInfo

func (m *MintRecord) GetStatus() MintRecord_Status {
	if m != nil {
		return m.Status
	}
	return MintRecord_STATUS_NONE
}

func (m *MintRecord) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *MintRecord) GetPayerAddress() string {
	if m != nil {
		return m.PayerAddress
	}
	return ""
}

func (m *MintRecord) GetPaymentDetails() *MintRecord_PaymentDetails {
	if m != nil {
		return m.PaymentDetails
	}
	return nil
}

func (m *MintRecord) GetMintingTransactionHash() string {
	if m != nil {
		return m.MintingTransactionHash
	}
	return ""
}

func (m *MintRecord) GetMintingDetails() *MintRecord_MintingDetails {
	if m != nil {
		return m.MintingDetails
	}
	return nil
}

func (m *MintRecord) GetTimestamps() *MintRecord_Timestamps {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *MintRecord) GetFlowerData() *Flower {
	if m != nil {
		return m.FlowerData
	}
	return nil
}

type MintRecord_PaymentDetails struct {
	Type                 MintRecord_PaymentDetails_PaymentType `protobuf:"varint,1,opt,name=type,proto3,enum=protobuf.MintRecord_PaymentDetails_PaymentType" json:"type,omitempty"`
	Value                int64                                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	StoreDBID            int64                                 `protobuf:"varint,3,opt,name=storeDBID,proto3" json:"storeDBID,omitempty"`
	ItemType             int64                                 `protobuf:"varint,4,opt,name=itemType,proto3" json:"itemType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-" datastore:"-"`
	XXX_unrecognized     []byte                                `json:"-" datastore:"-"`
	XXX_sizecache        int32                                 `json:"-" datastore:"-"`
}

func (m *MintRecord_PaymentDetails) Reset()         { *m = MintRecord_PaymentDetails{} }
func (m *MintRecord_PaymentDetails) String() string { return proto.CompactTextString(m) }
func (*MintRecord_PaymentDetails) ProtoMessage()    {}
func (*MintRecord_PaymentDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_219aa6949c8ae29b, []int{0, 0}
}

func (m *MintRecord_PaymentDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintRecord_PaymentDetails.Unmarshal(m, b)
}
func (m *MintRecord_PaymentDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintRecord_PaymentDetails.Marshal(b, m, deterministic)
}
func (m *MintRecord_PaymentDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintRecord_PaymentDetails.Merge(m, src)
}
func (m *MintRecord_PaymentDetails) XXX_Size() int {
	return xxx_messageInfo_MintRecord_PaymentDetails.Size(m)
}
func (m *MintRecord_PaymentDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_MintRecord_PaymentDetails.DiscardUnknown(m)
}

var xxx_messageInfo_MintRecord_PaymentDetails proto.InternalMessageInfo

func (m *MintRecord_PaymentDetails) GetType() MintRecord_PaymentDetails_PaymentType {
	if m != nil {
		return m.Type
	}
	return MintRecord_PaymentDetails_TYPE_ETH
}

func (m *MintRecord_PaymentDetails) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *MintRecord_PaymentDetails) GetStoreDBID() int64 {
	if m != nil {
		return m.StoreDBID
	}
	return 0
}

func (m *MintRecord_PaymentDetails) GetItemType() int64 {
	if m != nil {
		return m.ItemType
	}
	return 0
}

type MintRecord_MintingDetails struct {
	GasPrice             int64    `protobuf:"varint,1,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	GasLimit             int64    `protobuf:"varint,2,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	MinterAddress        string   `protobuf:"bytes,3,opt,name=minterAddress,proto3" json:"minterAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *MintRecord_MintingDetails) Reset()         { *m = MintRecord_MintingDetails{} }
func (m *MintRecord_MintingDetails) String() string { return proto.CompactTextString(m) }
func (*MintRecord_MintingDetails) ProtoMessage()    {}
func (*MintRecord_MintingDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_219aa6949c8ae29b, []int{0, 1}
}

func (m *MintRecord_MintingDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintRecord_MintingDetails.Unmarshal(m, b)
}
func (m *MintRecord_MintingDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintRecord_MintingDetails.Marshal(b, m, deterministic)
}
func (m *MintRecord_MintingDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintRecord_MintingDetails.Merge(m, src)
}
func (m *MintRecord_MintingDetails) XXX_Size() int {
	return xxx_messageInfo_MintRecord_MintingDetails.Size(m)
}
func (m *MintRecord_MintingDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_MintRecord_MintingDetails.DiscardUnknown(m)
}

var xxx_messageInfo_MintRecord_MintingDetails proto.InternalMessageInfo

func (m *MintRecord_MintingDetails) GetGasPrice() int64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *MintRecord_MintingDetails) GetGasLimit() int64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *MintRecord_MintingDetails) GetMinterAddress() string {
	if m != nil {
		return m.MinterAddress
	}
	return ""
}

type MintRecord_Timestamps struct {
	Started              int64    `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Completed            int64    `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	Error                int64    `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *MintRecord_Timestamps) Reset()         { *m = MintRecord_Timestamps{} }
func (m *MintRecord_Timestamps) String() string { return proto.CompactTextString(m) }
func (*MintRecord_Timestamps) ProtoMessage()    {}
func (*MintRecord_Timestamps) Descriptor() ([]byte, []int) {
	return fileDescriptor_219aa6949c8ae29b, []int{0, 2}
}

func (m *MintRecord_Timestamps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintRecord_Timestamps.Unmarshal(m, b)
}
func (m *MintRecord_Timestamps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintRecord_Timestamps.Marshal(b, m, deterministic)
}
func (m *MintRecord_Timestamps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintRecord_Timestamps.Merge(m, src)
}
func (m *MintRecord_Timestamps) XXX_Size() int {
	return xxx_messageInfo_MintRecord_Timestamps.Size(m)
}
func (m *MintRecord_Timestamps) XXX_DiscardUnknown() {
	xxx_messageInfo_MintRecord_Timestamps.DiscardUnknown(m)
}

var xxx_messageInfo_MintRecord_Timestamps proto.InternalMessageInfo

func (m *MintRecord_Timestamps) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *MintRecord_Timestamps) GetCompleted() int64 {
	if m != nil {
		return m.Completed
	}
	return 0
}

func (m *MintRecord_Timestamps) GetError() int64 {
	if m != nil {
		return m.Error
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuf.MintRecord_Status", MintRecord_Status_name, MintRecord_Status_value)
	proto.RegisterEnum("protobuf.MintRecord_PaymentDetails_PaymentType", MintRecord_PaymentDetails_PaymentType_name, MintRecord_PaymentDetails_PaymentType_value)
	proto.RegisterType((*MintRecord)(nil), "protobuf.MintRecord")
	proto.RegisterType((*MintRecord_PaymentDetails)(nil), "protobuf.MintRecord.PaymentDetails")
	proto.RegisterType((*MintRecord_MintingDetails)(nil), "protobuf.MintRecord.MintingDetails")
	proto.RegisterType((*MintRecord_Timestamps)(nil), "protobuf.MintRecord.Timestamps")
}

func init() { proto.RegisterFile("protobuf/mintrecord.proto", fileDescriptor_219aa6949c8ae29b) }

var fileDescriptor_219aa6949c8ae29b = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0x12, 0x41,
	0x14, 0xed, 0x96, 0x42, 0xe1, 0xd2, 0xae, 0x9b, 0x9b, 0xda, 0xac, 0x68, 0x22, 0x41, 0x1f, 0x88,
	0x0f, 0xd4, 0xb4, 0x89, 0xaf, 0x06, 0xcb, 0x9a, 0x36, 0x96, 0x42, 0x86, 0xe9, 0x83, 0xbe, 0x90,
	0x29, 0x4c, 0x71, 0x23, 0xfb, 0x91, 0x99, 0x41, 0xc3, 0xcf, 0xf4, 0x07, 0xf8, 0x5f, 0xcc, 0xcc,
	0x0e, 0xbb, 0x2c, 0xa9, 0xa6, 0x6f, 0x7b, 0xce, 0x3d, 0xf7, 0xf3, 0xcc, 0xc2, 0x8b, 0x54, 0x24,
	0x2a, 0xb9, 0x5f, 0x3d, 0x9c, 0x45, 0x61, 0xac, 0x04, 0x9f, 0x25, 0x62, 0xde, 0x33, 0x1c, 0xd6,
	0x37, 0xa1, 0xd6, 0xf3, 0x5c, 0xf4, 0xb0, 0x4c, 0x7e, 0x71, 0x91, 0x09, 0x3a, 0x7f, 0x0e, 0x01,
	0x86, 0x61, 0xac, 0x88, 0xc9, 0xc2, 0x0b, 0xa8, 0x49, 0xc5, 0xd4, 0x4a, 0xfa, 0x4e, 0xdb, 0xe9,
	0xba, 0xe7, 0x2f, 0x7b, 0x9b, 0xb4, 0x5e, 0xa1, 0xea, 0x4d, 0x8c, 0x84, 0x58, 0x29, 0xbe, 0x85,
	0xe3, 0xec, 0x6b, 0xc8, 0xa5, 0x64, 0x0b, 0xee, 0xef, 0xb7, 0x9d, 0x6e, 0x83, 0x94, 0x49, 0xec,
	0xc0, 0x51, 0xca, 0xd6, 0x5c, 0xf4, 0xe7, 0x73, 0xc1, 0xa5, 0xf4, 0x2b, 0x46, 0x54, 0xe2, 0xf0,
	0x0b, 0xb8, 0x29, 0x5b, 0x47, 0x3c, 0x56, 0x03, 0xae, 0x58, 0xb8, 0x94, 0xfe, 0x41, 0xdb, 0xe9,
	0x36, 0xcf, 0xdf, 0x3c, 0x3a, 0xc6, 0xb8, 0x24, 0x25, 0x3b, 0xa9, 0xf8, 0x01, 0x4e, 0xf5, 0x3d,
	0xc2, 0x78, 0x41, 0x05, 0x8b, 0x25, 0x9b, 0xa9, 0x30, 0x89, 0xaf, 0x98, 0xfc, 0xee, 0x57, 0x4d,
	0xeb, 0x7f, 0x44, 0xf5, 0x10, 0x36, 0xb2, 0x19, 0xa2, 0xf6, 0x9f, 0x21, 0x86, 0x25, 0x29, 0xd9,
	0x49, 0xc5, 0x8f, 0x00, 0x2a, 0x8c, 0xb8, 0x54, 0x2c, 0x4a, 0xa5, 0x5f, 0x37, 0x85, 0x5e, 0x3f,
	0x5a, 0x88, 0xe6, 0x32, 0xb2, 0x95, 0x82, 0xef, 0x01, 0x32, 0xc3, 0x06, 0x4c, 0x31, 0xbf, 0x61,
	0x0a, 0x78, 0x45, 0x81, 0xcf, 0x26, 0x46, 0xb6, 0x34, 0xad, 0xdf, 0x0e, 0xb8, 0xe5, 0xd3, 0xe0,
	0x25, 0x1c, 0xa8, 0x75, 0xca, 0xad, 0xa9, 0x67, 0x4f, 0xb8, 0xe6, 0x06, 0xd2, 0x75, 0xca, 0x89,
	0x49, 0xc6, 0x13, 0xa8, 0xfe, 0x64, 0xcb, 0x55, 0x66, 0x6f, 0x85, 0x64, 0x00, 0x5f, 0x41, 0x43,
	0xaa, 0x44, 0xf0, 0xc1, 0xa7, 0xeb, 0x81, 0xf1, 0xb4, 0x42, 0x0a, 0x02, 0x5b, 0x50, 0x0f, 0x15,
	0x8f, 0x74, 0x15, 0x63, 0x65, 0x85, 0xe4, 0xb8, 0xf3, 0x0e, 0x9a, 0x5b, 0x4d, 0xf0, 0x08, 0xea,
	0xf4, 0xeb, 0x38, 0x98, 0x06, 0xf4, 0xca, 0xdb, 0xc3, 0x63, 0x68, 0x18, 0x34, 0x09, 0x82, 0x81,
	0xe7, 0xb4, 0x62, 0x70, 0xcb, 0x87, 0xd6, 0x95, 0x17, 0x4c, 0x8e, 0x45, 0x38, 0xcb, 0xd6, 0xaa,
	0x90, 0x1c, 0xdb, 0xd8, 0x4d, 0x18, 0x85, 0xca, 0x0e, 0x9b, 0x63, 0xfd, 0x58, 0xb5, 0x45, 0xbb,
	0xef, 0xb0, 0x4c, 0xb6, 0xbe, 0x01, 0x14, 0x7e, 0xa0, 0x0f, 0x87, 0x52, 0x31, 0xa1, 0xf8, 0xdc,
	0xb6, 0xda, 0x40, 0xbd, 0xfd, 0x2c, 0x89, 0xd2, 0x25, 0xd7, 0xb1, 0xac, 0x55, 0x41, 0xe8, 0x8b,
	0x71, 0x21, 0x12, 0x61, 0xef, 0x92, 0x81, 0xce, 0x0f, 0xa8, 0x65, 0x3f, 0x10, 0x3e, 0x83, 0xe6,
	0x84, 0xf6, 0xe9, 0xdd, 0x64, 0x7a, 0x3b, 0xba, 0x0d, 0xbc, 0x3d, 0x44, 0x70, 0x2d, 0x31, 0xa1,
	0x7d, 0x42, 0xf5, 0xea, 0x78, 0x02, 0x9e, 0xe5, 0x2e, 0x47, 0xc3, 0xf1, 0x4d, 0xa0, 0xd9, 0x7d,
	0x74, 0x01, 0x2c, 0x1b, 0x10, 0xe2, 0x55, 0xf1, 0x14, 0xb0, 0xc0, 0x53, 0x7a, 0x3d, 0x0c, 0x46,
	0x77, 0xd4, 0xab, 0xdd, 0xd7, 0x8c, 0xd5, 0x17, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x44,
	0x49, 0xdb, 0x24, 0x04, 0x00, 0x00,
}
