// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/rarityleaderboard.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RarityLeaderboard struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Common               int32    `protobuf:"varint,3,opt,name=common,proto3" json:"common,omitempty"`
	Unusual              int32    `protobuf:"varint,4,opt,name=unusual,proto3" json:"unusual,omitempty"`
	Rare                 int32    `protobuf:"varint,5,opt,name=rare,proto3" json:"rare,omitempty"`
	Epic                 int32    `protobuf:"varint,6,opt,name=epic,proto3" json:"epic,omitempty"`
	Legendary            int32    `protobuf:"varint,7,opt,name=legendary,proto3" json:"legendary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *RarityLeaderboard) Reset()         { *m = RarityLeaderboard{} }
func (m *RarityLeaderboard) String() string { return proto.CompactTextString(m) }
func (*RarityLeaderboard) ProtoMessage()    {}
func (*RarityLeaderboard) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6c6222a5ba605a5, []int{0}
}

func (m *RarityLeaderboard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RarityLeaderboard.Unmarshal(m, b)
}
func (m *RarityLeaderboard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RarityLeaderboard.Marshal(b, m, deterministic)
}
func (m *RarityLeaderboard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RarityLeaderboard.Merge(m, src)
}
func (m *RarityLeaderboard) XXX_Size() int {
	return xxx_messageInfo_RarityLeaderboard.Size(m)
}
func (m *RarityLeaderboard) XXX_DiscardUnknown() {
	xxx_messageInfo_RarityLeaderboard.DiscardUnknown(m)
}

var xxx_messageInfo_RarityLeaderboard proto.InternalMessageInfo

func (m *RarityLeaderboard) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *RarityLeaderboard) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RarityLeaderboard) GetCommon() int32 {
	if m != nil {
		return m.Common
	}
	return 0
}

func (m *RarityLeaderboard) GetUnusual() int32 {
	if m != nil {
		return m.Unusual
	}
	return 0
}

func (m *RarityLeaderboard) GetRare() int32 {
	if m != nil {
		return m.Rare
	}
	return 0
}

func (m *RarityLeaderboard) GetEpic() int32 {
	if m != nil {
		return m.Epic
	}
	return 0
}

func (m *RarityLeaderboard) GetLegendary() int32 {
	if m != nil {
		return m.Legendary
	}
	return 0
}

func init() {
	proto.RegisterType((*RarityLeaderboard)(nil), "protobuf.RarityLeaderboard")
}

func init() { proto.RegisterFile("protobuf/rarityleaderboard.proto", fileDescriptor_b6c6222a5ba605a5) }

var fileDescriptor_b6c6222a5ba605a5 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x3f, 0xce, 0x82, 0x40,
	0x10, 0x47, 0xb3, 0xdf, 0xc7, 0x1f, 0xd9, 0xce, 0x8d, 0x31, 0x53, 0x58, 0x10, 0x2b, 0x2a, 0x2d,
	0xbc, 0x86, 0x15, 0x37, 0x58, 0x60, 0x34, 0x24, 0xcb, 0x0e, 0x19, 0x77, 0x63, 0x38, 0x99, 0xd7,
	0x33, 0x0c, 0x12, 0xba, 0x79, 0xef, 0xf7, 0x9a, 0xd1, 0xe5, 0xc8, 0x14, 0xa8, 0x89, 0x8f, 0x2b,
	0x5b, 0xee, 0xc3, 0xe4, 0xd0, 0x76, 0xc8, 0x0d, 0x59, 0xee, 0x2e, 0x32, 0x99, 0xdd, 0x5a, 0x9c,
	0x3f, 0x4a, 0xef, 0x6b, 0xa9, 0xee, 0x5b, 0x65, 0x0e, 0x3a, 0xa5, 0xb7, 0x47, 0x06, 0x55, 0xaa,
	0xaa, 0xa8, 0x17, 0x98, 0x6d, 0xa0, 0x60, 0x1d, 0xfc, 0x95, 0xaa, 0x4a, 0xeb, 0x05, 0xcc, 0x51,
	0x67, 0x2d, 0x0d, 0x03, 0x79, 0xf8, 0x17, 0xfd, 0x23, 0x03, 0x3a, 0x8f, 0x3e, 0xbe, 0xa2, 0x75,
	0x90, 0xc8, 0xb0, 0xa2, 0x31, 0x3a, 0x61, 0xcb, 0x08, 0xa9, 0x68, 0xb9, 0x67, 0x87, 0x63, 0xdf,
	0x42, 0xb6, 0xb8, 0xf9, 0x36, 0x27, 0x5d, 0x38, 0x7c, 0xa2, 0xef, 0x2c, 0x4f, 0x90, 0xcb, 0xb0,
	0x89, 0x26, 0x93, 0x1f, 0x6e, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x41, 0x22, 0xb5, 0xee,
	0x00, 0x00, 0x00,
}
