/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.protobuf.RarityLeaderboard', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protobuf.RarityLeaderboard = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.protobuf.RarityLeaderboard, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.protobuf.RarityLeaderboard.displayName = 'proto.protobuf.RarityLeaderboard';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protobuf.RarityLeaderboard.prototype.toObject = function(opt_includeInstance) {
  return proto.protobuf.RarityLeaderboard.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protobuf.RarityLeaderboard} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuf.RarityLeaderboard.toObject = function(includeInstance, msg) {
  var f, obj = {
    owner: jspb.Message.getFieldWithDefault(msg, 1, ""),
    total: jspb.Message.getFieldWithDefault(msg, 2, 0),
    common: jspb.Message.getFieldWithDefault(msg, 3, 0),
    unusual: jspb.Message.getFieldWithDefault(msg, 4, 0),
    rare: jspb.Message.getFieldWithDefault(msg, 5, 0),
    epic: jspb.Message.getFieldWithDefault(msg, 6, 0),
    legendary: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protobuf.RarityLeaderboard}
 */
proto.protobuf.RarityLeaderboard.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protobuf.RarityLeaderboard;
  return proto.protobuf.RarityLeaderboard.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protobuf.RarityLeaderboard} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protobuf.RarityLeaderboard}
 */
proto.protobuf.RarityLeaderboard.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwner(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotal(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCommon(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUnusual(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRare(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEpic(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLegendary(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protobuf.RarityLeaderboard.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protobuf.RarityLeaderboard.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protobuf.RarityLeaderboard} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protobuf.RarityLeaderboard.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOwner();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCommon();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getUnusual();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getRare();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getEpic();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getLegendary();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
};


/**
 * optional string owner = 1;
 * @return {string}
 */
proto.protobuf.RarityLeaderboard.prototype.getOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.protobuf.RarityLeaderboard.prototype.setOwner = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 total = 2;
 * @return {number}
 */
proto.protobuf.RarityLeaderboard.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.protobuf.RarityLeaderboard.prototype.setTotal = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 common = 3;
 * @return {number}
 */
proto.protobuf.RarityLeaderboard.prototype.getCommon = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.protobuf.RarityLeaderboard.prototype.setCommon = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 unusual = 4;
 * @return {number}
 */
proto.protobuf.RarityLeaderboard.prototype.getUnusual = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.protobuf.RarityLeaderboard.prototype.setUnusual = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 rare = 5;
 * @return {number}
 */
proto.protobuf.RarityLeaderboard.prototype.getRare = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.protobuf.RarityLeaderboard.prototype.setRare = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 epic = 6;
 * @return {number}
 */
proto.protobuf.RarityLeaderboard.prototype.getEpic = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.protobuf.RarityLeaderboard.prototype.setEpic = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 legendary = 7;
 * @return {number}
 */
proto.protobuf.RarityLeaderboard.prototype.getLegendary = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.protobuf.RarityLeaderboard.prototype.setLegendary = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


goog.object.extend(exports, proto.protobuf);
