// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/servicecommon.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyRequest struct {
	SourceAccount        string   `protobuf:"bytes,1,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_add8bcf2fb874c98, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

func (m *EmptyRequest) GetSourceAccount() string {
	if m != nil {
		return m.SourceAccount
	}
	return ""
}

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_add8bcf2fb874c98, []int{1}
}

func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (m *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(m, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

type SingleInt64 struct {
	SourceAccount        string   `protobuf:"bytes,1,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	Input                int64    `protobuf:"varint,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *SingleInt64) Reset()         { *m = SingleInt64{} }
func (m *SingleInt64) String() string { return proto.CompactTextString(m) }
func (*SingleInt64) ProtoMessage()    {}
func (*SingleInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_add8bcf2fb874c98, []int{2}
}

func (m *SingleInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleInt64.Unmarshal(m, b)
}
func (m *SingleInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleInt64.Marshal(b, m, deterministic)
}
func (m *SingleInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleInt64.Merge(m, src)
}
func (m *SingleInt64) XXX_Size() int {
	return xxx_messageInfo_SingleInt64.Size(m)
}
func (m *SingleInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleInt64.DiscardUnknown(m)
}

var xxx_messageInfo_SingleInt64 proto.InternalMessageInfo

func (m *SingleInt64) GetSourceAccount() string {
	if m != nil {
		return m.SourceAccount
	}
	return ""
}

func (m *SingleInt64) GetInput() int64 {
	if m != nil {
		return m.Input
	}
	return 0
}

type RepeatedInt64 struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *RepeatedInt64) Reset()         { *m = RepeatedInt64{} }
func (m *RepeatedInt64) String() string { return proto.CompactTextString(m) }
func (*RepeatedInt64) ProtoMessage()    {}
func (*RepeatedInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_add8bcf2fb874c98, []int{3}
}

func (m *RepeatedInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedInt64.Unmarshal(m, b)
}
func (m *RepeatedInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedInt64.Marshal(b, m, deterministic)
}
func (m *RepeatedInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedInt64.Merge(m, src)
}
func (m *RepeatedInt64) XXX_Size() int {
	return xxx_messageInfo_RepeatedInt64.Size(m)
}
func (m *RepeatedInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedInt64.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedInt64 proto.InternalMessageInfo

func (m *RepeatedInt64) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type SingleString struct {
	SourceAccount        string   `protobuf:"bytes,1,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *SingleString) Reset()         { *m = SingleString{} }
func (m *SingleString) String() string { return proto.CompactTextString(m) }
func (*SingleString) ProtoMessage()    {}
func (*SingleString) Descriptor() ([]byte, []int) {
	return fileDescriptor_add8bcf2fb874c98, []int{4}
}

func (m *SingleString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleString.Unmarshal(m, b)
}
func (m *SingleString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleString.Marshal(b, m, deterministic)
}
func (m *SingleString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleString.Merge(m, src)
}
func (m *SingleString) XXX_Size() int {
	return xxx_messageInfo_SingleString.Size(m)
}
func (m *SingleString) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleString.DiscardUnknown(m)
}

var xxx_messageInfo_SingleString proto.InternalMessageInfo

func (m *SingleString) GetSourceAccount() string {
	if m != nil {
		return m.SourceAccount
	}
	return ""
}

func (m *SingleString) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "protobuf.EmptyRequest")
	proto.RegisterType((*EmptyReply)(nil), "protobuf.EmptyReply")
	proto.RegisterType((*SingleInt64)(nil), "protobuf.SingleInt64")
	proto.RegisterType((*RepeatedInt64)(nil), "protobuf.RepeatedInt64")
	proto.RegisterType((*SingleString)(nil), "protobuf.SingleString")
}

func init() { proto.RegisterFile("protobuf/servicecommon.proto", fileDescriptor_add8bcf2fb874c98) }

var fileDescriptor_add8bcf2fb874c98 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x4d, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x03, 0x0b, 0x0b, 0x71, 0xc0, 0x64, 0x95, 0x4c, 0xb9, 0x78, 0x5c, 0x73, 0x0b,
	0x4a, 0x2a, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x54, 0xb9, 0xf8, 0x8a, 0xf3, 0x4b,
	0x8b, 0x92, 0x53, 0xe3, 0x13, 0x93, 0x93, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x78, 0x21, 0xa2, 0x8e, 0x10, 0x41, 0x25, 0x1e, 0x2e, 0x2e, 0xa8, 0xb6, 0x82, 0x9c,
	0x4a, 0x25, 0x2f, 0x2e, 0xee, 0xe0, 0xcc, 0xbc, 0xf4, 0x9c, 0x54, 0xcf, 0xbc, 0x12, 0x33, 0x13,
	0x22, 0xcd, 0x10, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x2b, 0x28, 0x2d, 0x91, 0x60, 0x52, 0x60, 0xd4,
	0x60, 0x0e, 0x82, 0x70, 0x94, 0x94, 0xb9, 0x78, 0x83, 0x52, 0x0b, 0x52, 0x13, 0x4b, 0x52, 0x53,
	0x20, 0xa6, 0x09, 0x71, 0xb1, 0xe4, 0x64, 0x16, 0x83, 0xcc, 0x60, 0xd6, 0x60, 0x0e, 0x02, 0xb3,
	0x95, 0xbc, 0xb9, 0x78, 0x20, 0x16, 0x06, 0x97, 0x14, 0x65, 0xe6, 0xa5, 0x93, 0x65, 0x23, 0x27,
	0xd4, 0xc6, 0x24, 0x36, 0x70, 0x60, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x64, 0xe9, 0xa0,
	0x3f, 0x33, 0x01, 0x00, 0x00,
}
