// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/tokeninfo.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TokenInfo struct {
	ContractName         string   `protobuf:"bytes,1,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageURL             string   `protobuf:"bytes,3,opt,name=image_u_r_l,json=imageURL,proto3" json:"image_u_r_l,omitempty"`
	LinkURL              string   `protobuf:"bytes,4,opt,name=link_u_r_l,json=linkURL,proto3" json:"link_u_r_l,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *TokenInfo) Reset()         { *m = TokenInfo{} }
func (m *TokenInfo) String() string { return proto.CompactTextString(m) }
func (*TokenInfo) ProtoMessage()    {}
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d3518bbd643c5e, []int{0}
}

func (m *TokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenInfo.Unmarshal(m, b)
}
func (m *TokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenInfo.Marshal(b, m, deterministic)
}
func (m *TokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenInfo.Merge(m, src)
}
func (m *TokenInfo) XXX_Size() int {
	return xxx_messageInfo_TokenInfo.Size(m)
}
func (m *TokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TokenInfo proto.InternalMessageInfo

func (m *TokenInfo) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *TokenInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TokenInfo) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *TokenInfo) GetLinkURL() string {
	if m != nil {
		return m.LinkURL
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenInfo)(nil), "protobuf.TokenInfo")
}

func init() { proto.RegisterFile("protobuf/tokeninfo.proto", fileDescriptor_f7d3518bbd643c5e) }

var fileDescriptor_f7d3518bbd643c5e = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0xc9, 0xcf, 0x4e, 0xcd, 0xcb, 0xcc, 0x4b, 0xcb, 0xd7, 0x03,
	0x0b, 0x09, 0x71, 0xc0, 0x64, 0x94, 0x1a, 0x18, 0xb9, 0x38, 0x43, 0x40, 0xb2, 0x9e, 0x79, 0x69,
	0xf9, 0x42, 0xca, 0x5c, 0xbc, 0xc9, 0xf9, 0x79, 0x25, 0x45, 0x89, 0xc9, 0x25, 0xf1, 0x79, 0x89,
	0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x3c, 0x30, 0x41, 0xbf, 0xc4, 0xdc, 0x54,
	0x21, 0x21, 0x2e, 0x16, 0xb0, 0x1c, 0x13, 0x58, 0x0e, 0xcc, 0x16, 0x92, 0xe5, 0xe2, 0xce, 0xcc,
	0x4d, 0x4c, 0x4f, 0x8d, 0x2f, 0x8d, 0x2f, 0x8a, 0xcf, 0x91, 0x60, 0x06, 0x4b, 0x71, 0x80, 0x85,
	0x42, 0x83, 0x7c, 0x84, 0xa4, 0xb9, 0xb8, 0x72, 0x32, 0xf3, 0xb2, 0xa1, 0xb2, 0x2c, 0x60, 0x59,
	0x76, 0x90, 0x48, 0x68, 0x90, 0x4f, 0x12, 0x1b, 0xd8, 0x31, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf0, 0x3f, 0xb9, 0x12, 0xaf, 0x00, 0x00, 0x00,
}
