// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/userinfo.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Database key is eth address
type UserInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Bio                  string   `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Profile              string   `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Homepage             string   `protobuf:"bytes,5,opt,name=homepage,proto3" json:"homepage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b99708cd1932392, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *UserInfo) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *UserInfo) GetHomepage() string {
	if m != nil {
		return m.Homepage
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "protobuf.UserInfo")
}

func init() { proto.RegisterFile("protobuf/userinfo.proto", fileDescriptor_4b99708cd1932392) }

var fileDescriptor_4b99708cd1932392 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x2d, 0x4e, 0x2d, 0xca, 0xcc, 0x4b, 0xcb, 0xd7, 0x03, 0x8b,
	0x08, 0x71, 0xc0, 0x24, 0x94, 0x6a, 0xb8, 0x38, 0x42, 0x8b, 0x53, 0x8b, 0x3c, 0xf3, 0xd2, 0xf2,
	0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0,
	0x6c, 0x21, 0x11, 0x2e, 0xd6, 0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x26, 0xb0, 0x20, 0x84, 0x23,
	0x24, 0xc0, 0xc5, 0x9c, 0x94, 0x99, 0x2f, 0xc1, 0x0c, 0x16, 0x03, 0x31, 0x85, 0x24, 0xb8, 0xd8,
	0x0b, 0x8a, 0xf2, 0xd3, 0x32, 0x73, 0x52, 0x25, 0x58, 0xc0, 0xa2, 0x30, 0xae, 0x90, 0x14, 0x17,
	0x47, 0x46, 0x7e, 0x6e, 0x6a, 0x41, 0x62, 0x7a, 0xaa, 0x04, 0x2b, 0x58, 0x0a, 0xce, 0x4f, 0x62,
	0x03, 0xbb, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x09, 0x5e, 0x10, 0xa9, 0x00, 0x00,
	0x00,
}
